import { semanticCube } from './semanticCube'

describe('it tests all semantic cube operations', () => {
    it('on ints', () => {
        expect(semanticCube['+']['int']['int']).toBe('int')
        expect(semanticCube['-']['int']['int']).toBe('int')
        expect(semanticCube['*']['int']['int']).toBe('int')
        expect(semanticCube['/']['int']['int']).toBe('float')
        expect(semanticCube['<']['int']['int']).toBe('bool')
        expect(semanticCube['>']['int']['int']).toBe('bool')
        expect(semanticCube['<=']['int']['int']).toBe('bool')
        expect(semanticCube['>=']['int']['int']).toBe('bool')
        expect(semanticCube['==']['int']['int']).toBe('bool')
        expect(semanticCube['!=']['int']['int']).toBe('bool')
        expect(semanticCube['&&']['int']['int']).toBe('Type Error')
        expect(semanticCube['||']['int']['int']).toBe('Type Error')

        expect(semanticCube['+']['int']['float']).toBe('float')
        expect(semanticCube['-']['int']['float']).toBe('float')
        expect(semanticCube['*']['int']['float']).toBe('float')
        expect(semanticCube['/']['int']['float']).toBe('float')
        expect(semanticCube['<']['int']['float']).toBe('bool')
        expect(semanticCube['>']['int']['float']).toBe('bool')
        expect(semanticCube['<=']['int']['float']).toBe('bool')
        expect(semanticCube['>=']['int']['float']).toBe('bool')
        expect(semanticCube['==']['int']['float']).toBe('bool')
        expect(semanticCube['!=']['int']['float']).toBe('bool')
        expect(semanticCube['&&']['int']['float']).toBe('Type Error')
        expect(semanticCube['||']['int']['float']).toBe('Type Error')

        expect(semanticCube['+']['int']['bool']).toBe('Type Error')
        expect(semanticCube['-']['int']['bool']).toBe('Type Error')
        expect(semanticCube['*']['int']['bool']).toBe('Type Error')
        expect(semanticCube['/']['int']['bool']).toBe('Type Error')
        expect(semanticCube['<']['int']['bool']).toBe('Type Error')
        expect(semanticCube['>']['int']['bool']).toBe('Type Error')
        expect(semanticCube['<=']['int']['bool']).toBe('Type Error')
        expect(semanticCube['>=']['int']['bool']).toBe('Type Error')
        expect(semanticCube['==']['int']['bool']).toBe('Type Error')
        expect(semanticCube['!=']['int']['bool']).toBe('Type Error')
        expect(semanticCube['&&']['int']['bool']).toBe('Type Error')
        expect(semanticCube['||']['int']['bool']).toBe('Type Error')

        expect(semanticCube['+']['int']['string']).toBe('Type Error')
        expect(semanticCube['-']['int']['string']).toBe('Type Error')
        expect(semanticCube['*']['int']['string']).toBe('Type Error')
        expect(semanticCube['/']['int']['string']).toBe('Type Error')
        expect(semanticCube['<']['int']['string']).toBe('Type Error')
        expect(semanticCube['>']['int']['string']).toBe('Type Error')
        expect(semanticCube['<=']['int']['string']).toBe('Type Error')
        expect(semanticCube['>=']['int']['string']).toBe('Type Error')
        expect(semanticCube['==']['int']['string']).toBe('Type Error')
        expect(semanticCube['!=']['int']['string']).toBe('Type Error')
        expect(semanticCube['&&']['int']['string']).toBe('Type Error')
        expect(semanticCube['||']['int']['string']).toBe('Type Error')

    })
    it('on floats', () => {
        expect(semanticCube['+']['float']['int']).toBe('float')
        expect(semanticCube['-']['float']['int']).toBe('float')
        expect(semanticCube['*']['float']['int']).toBe('float')
        expect(semanticCube['/']['float']['int']).toBe('float')
        expect(semanticCube['<']['float']['int']).toBe('bool')
        expect(semanticCube['>']['float']['int']).toBe('bool')
        expect(semanticCube['<=']['float']['int']).toBe('bool')
        expect(semanticCube['>=']['float']['int']).toBe('bool')
        expect(semanticCube['==']['float']['int']).toBe('bool')
        expect(semanticCube['!=']['float']['int']).toBe('bool')
        expect(semanticCube['&&']['float']['int']).toBe('Type Error')
        expect(semanticCube['||']['float']['int']).toBe('Type Error')

        expect(semanticCube['+']['float']['float']).toBe('float')
        expect(semanticCube['-']['float']['float']).toBe('float')
        expect(semanticCube['*']['float']['float']).toBe('float')
        expect(semanticCube['/']['float']['float']).toBe('float')
        expect(semanticCube['<']['float']['float']).toBe('bool')
        expect(semanticCube['>']['float']['float']).toBe('bool')
        expect(semanticCube['<=']['float']['float']).toBe('bool')
        expect(semanticCube['>=']['float']['float']).toBe('bool')
        expect(semanticCube['==']['float']['float']).toBe('bool')
        expect(semanticCube['!=']['float']['float']).toBe('bool')
        expect(semanticCube['&&']['float']['float']).toBe('Type Error')
        expect(semanticCube['||']['float']['float']).toBe('Type Error')

        expect(semanticCube['+']['float']['string']).toBe('Type Error')
        expect(semanticCube['-']['float']['string']).toBe('Type Error')
        expect(semanticCube['*']['float']['string']).toBe('Type Error')
        expect(semanticCube['/']['float']['string']).toBe('Type Error')
        expect(semanticCube['<']['float']['string']).toBe('Type Error')
        expect(semanticCube['>']['float']['string']).toBe('Type Error')
        expect(semanticCube['<=']['float']['string']).toBe('Type Error')
        expect(semanticCube['>=']['float']['string']).toBe('Type Error')
        expect(semanticCube['==']['float']['string']).toBe('Type Error')
        expect(semanticCube['!=']['float']['string']).toBe('Type Error')
        expect(semanticCube['&&']['float']['string']).toBe('Type Error')
        expect(semanticCube['||']['float']['string']).toBe('Type Error')

        expect(semanticCube['-']['float']['bool']).toBe('Type Error')
        expect(semanticCube['+']['float']['bool']).toBe('Type Error')
        expect(semanticCube['*']['float']['bool']).toBe('Type Error')
        expect(semanticCube['/']['float']['bool']).toBe('Type Error')
        expect(semanticCube['<']['float']['bool']).toBe('Type Error')
        expect(semanticCube['>']['float']['bool']).toBe('Type Error')
        expect(semanticCube['<=']['float']['bool']).toBe('Type Error')
        expect(semanticCube['>=']['float']['bool']).toBe('Type Error')
        expect(semanticCube['==']['float']['bool']).toBe('Type Error')
        expect(semanticCube['!=']['float']['bool']).toBe('Type Error')
        expect(semanticCube['&&']['float']['bool']).toBe('Type Error')
        expect(semanticCube['||']['float']['bool']).toBe('Type Error')

    })
    it('on string', () => {
        expect(semanticCube['+']['string']['string']).toBe('string')
        expect(semanticCube['-']['string']['string']).toBe('Type Error')
        expect(semanticCube['*']['string']['string']).toBe('Type Error')
        expect(semanticCube['/']['string']['string']).toBe('Type Error')
        expect(semanticCube['<']['string']['string']).toBe('Type Error')
        expect(semanticCube['>']['string']['string']).toBe('Type Error')
        expect(semanticCube['<=']['string']['string']).toBe('Type Error')
        expect(semanticCube['>=']['string']['string']).toBe('Type Error')
        expect(semanticCube['==']['string']['string']).toBe('bool')
        expect(semanticCube['!=']['string']['string']).toBe('bool')
        expect(semanticCube['&&']['string']['string']).toBe('Type Error')
        expect(semanticCube['||']['string']['string']).toBe('Type Error')

        expect(semanticCube['+']['string']['int']).toBe('Type Error')
        expect(semanticCube['-']['string']['int']).toBe('Type Error')
        expect(semanticCube['*']['string']['int']).toBe('Type Error')
        expect(semanticCube['/']['string']['int']).toBe('Type Error')
        expect(semanticCube['<']['string']['int']).toBe('Type Error')
        expect(semanticCube['>']['string']['int']).toBe('Type Error')
        expect(semanticCube['<=']['string']['int']).toBe('Type Error')
        expect(semanticCube['>=']['string']['int']).toBe('Type Error')
        expect(semanticCube['==']['string']['int']).toBe('Type Error')
        expect(semanticCube['!=']['string']['int']).toBe('Type Error')
        expect(semanticCube['&&']['string']['int']).toBe('Type Error')
        expect(semanticCube['||']['string']['int']).toBe('Type Error')

        expect(semanticCube['+']['string']['float']).toBe('Type Error')
        expect(semanticCube['-']['string']['float']).toBe('Type Error')
        expect(semanticCube['*']['string']['float']).toBe('Type Error')
        expect(semanticCube['/']['string']['float']).toBe('Type Error')
        expect(semanticCube['<']['string']['float']).toBe('Type Error')
        expect(semanticCube['>']['string']['float']).toBe('Type Error')
        expect(semanticCube['<=']['string']['float']).toBe('Type Error')
        expect(semanticCube['>=']['string']['float']).toBe('Type Error')
        expect(semanticCube['==']['string']['float']).toBe('Type Error')
        expect(semanticCube['!=']['string']['float']).toBe('Type Error')
        expect(semanticCube['&&']['string']['float']).toBe('Type Error')
        expect(semanticCube['||']['string']['float']).toBe('Type Error')

        expect(semanticCube['+']['string']['bool']).toBe('Type Error')
        expect(semanticCube['-']['string']['bool']).toBe('Type Error')
        expect(semanticCube['*']['string']['bool']).toBe('Type Error')
        expect(semanticCube['/']['string']['bool']).toBe('Type Error')
        expect(semanticCube['<']['string']['bool']).toBe('Type Error')
        expect(semanticCube['>']['string']['bool']).toBe('Type Error')
        expect(semanticCube['<=']['string']['bool']).toBe('Type Error')
        expect(semanticCube['>=']['string']['bool']).toBe('Type Error')
        expect(semanticCube['==']['string']['bool']).toBe('Type Error')
        expect(semanticCube['!=']['string']['bool']).toBe('Type Error')
        expect(semanticCube['&&']['string']['bool']).toBe('Type Error')
        expect(semanticCube['||']['string']['bool']).toBe('Type Error')
    })
    it('on bool', () => {
        expect(semanticCube['+']['bool']['bool']).toBe('Type Error')
        expect(semanticCube['-']['bool']['bool']).toBe('Type Error')
        expect(semanticCube['*']['bool']['bool']).toBe('Type Error')
        expect(semanticCube['/']['bool']['bool']).toBe('Type Error')
        expect(semanticCube['<']['bool']['bool']).toBe('Type Error')
        expect(semanticCube['>']['bool']['bool']).toBe('Type Error')
        expect(semanticCube['<=']['bool']['bool']).toBe('Type Error')
        expect(semanticCube['>=']['bool']['bool']).toBe('Type Error')
        expect(semanticCube['==']['bool']['bool']).toBe('bool')
        expect(semanticCube['!=']['bool']['bool']).toBe('bool')
        expect(semanticCube['&&']['bool']['bool']).toBe('bool')
        expect(semanticCube['||']['bool']['bool']).toBe('bool')

        expect(semanticCube['+']['bool']['int']).toBe('Type Error')
        expect(semanticCube['-']['bool']['int']).toBe('Type Error')
        expect(semanticCube['*']['bool']['int']).toBe('Type Error')
        expect(semanticCube['/']['bool']['int']).toBe('Type Error')
        expect(semanticCube['<']['bool']['int']).toBe('Type Error')
        expect(semanticCube['>']['bool']['int']).toBe('Type Error')
        expect(semanticCube['<=']['bool']['int']).toBe('Type Error')
        expect(semanticCube['>=']['bool']['int']).toBe('Type Error')
        expect(semanticCube['==']['bool']['int']).toBe('Type Error')
        expect(semanticCube['!=']['bool']['int']).toBe('Type Error')
        expect(semanticCube['&&']['bool']['int']).toBe('Type Error')
        expect(semanticCube['||']['bool']['int']).toBe('Type Error')

        expect(semanticCube['+']['bool']['string']).toBe('Type Error')
        expect(semanticCube['-']['bool']['string']).toBe('Type Error')
        expect(semanticCube['*']['bool']['string']).toBe('Type Error')
        expect(semanticCube['/']['bool']['string']).toBe('Type Error')
        expect(semanticCube['<']['bool']['string']).toBe('Type Error')
        expect(semanticCube['>']['bool']['string']).toBe('Type Error')
        expect(semanticCube['<=']['bool']['string']).toBe('Type Error')
        expect(semanticCube['>=']['bool']['string']).toBe('Type Error')
        expect(semanticCube['==']['bool']['string']).toBe('Type Error')
        expect(semanticCube['!=']['bool']['string']).toBe('Type Error')
        expect(semanticCube['&&']['bool']['string']).toBe('Type Error')
        expect(semanticCube['||']['bool']['string']).toBe('Type Error')

        expect(semanticCube['+']['bool']['float']).toBe('Type Error')
        expect(semanticCube['-']['bool']['float']).toBe('Type Error')
        expect(semanticCube['*']['bool']['float']).toBe('Type Error')
        expect(semanticCube['/']['bool']['float']).toBe('Type Error')
        expect(semanticCube['<']['bool']['float']).toBe('Type Error')
        expect(semanticCube['>']['bool']['float']).toBe('Type Error')
        expect(semanticCube['<=']['bool']['float']).toBe('Type Error')
        expect(semanticCube['>=']['bool']['float']).toBe('Type Error')
        expect(semanticCube['==']['bool']['float']).toBe('Type Error')
        expect(semanticCube['!=']['bool']['float']).toBe('Type Error')
        expect(semanticCube['&&']['bool']['float']).toBe('Type Error')
        expect(semanticCube['||']['bool']['float']).toBe('Type Error')
    })
})